<div class="theme-layout">
	<div class="page-title style3" style="border-bottom:#2e2729 solid 2em;">
		<img src="/images/banners/gestion_desarrollo_web.jpg" alt="" />
		<a href="/home#work" title="" style="color:#b92444;">PRODUCTOS <i class="fa fa-long-arrow-right" style="color:#b92444;"></i></a>
		<div class="container">
		<h1 style="color:#f2e8eb;">DESARROLLO WEB</h1>
		<p>Una web, es símbolo de presencia y <br>
		oportunidad de ventas para tu negocio
		</p>		
		</div>
		<div>
			<a href="/home">
				<div class="logo" style="background-color: #fff;">
						<div style="padding: 0em 0.2em;">
							  <img src="/images/logo.jpg" alt="" width="25"/>
						</div>
						<div>
							 <span style="color:#2084c8;">Flex</span><span  style="color:#0bb8ce;">Zinn</span>
						</div>
				</div>		
			</a>		
		</div>		
	</div>

	<section>
		<div class="block less-spacing">
			<div class="container">
				<div class="row">
					<div class="col s12 m12 l12 column">
							<div class="big-title" style="margin-bottom:0px;">
								<div class="row">
										<div class="col s12 m12 l5">
										<h2>PÁGINAS WEB<span>Ideas / Diseño / Desarrollo</span></h2>
											
									</div>
									
									<div class="col s12 m12 l7">
										<span>Calidad, Agilidad, Rentabilidad</span>
										<p>Su página web es la carta de presentación ante el mundo. La calidad y eficiencia de su sitio web constituyen el camino para potenciar las ventas sus productos y servicios.
                                         Generamos ideas, planificamos, diseñamos y desarrollamos la web que impulsará y elevará las ventas en su negocio.
										</p>
									</div>
								</div>
							</div><!-- Big Title -->
		                    <div class="tags-share" style="padding:0;">
								<div class="tags-share-inner">
									<div class="tags" >
										<a href="#contact" title="" class="btnCall" style="background-color:#b92444;border-color:#b92444;">CONSULTAS EN LÍNEA</a>
									</div><!-- Tags -->
									<div class="share">
										<span>SHARE</span>
										<a href="#" title=""><i class="fa fa-twitter"></i></a>
										<a href="#" title=""><i class="fa fa-facebook"></i></a>
										<a href="#" title=""><i class="fa fa-google-plus"></i></a>
									</div><!-- Share -->
								</div>
							</div><!-- Tags Share -->						
							
							<div class="col s12 m12 l12 column">
								<div class="related-posts">
									<div class="container">
										<div class="row">
											<div class="col s12 m12 l3">
												<h4 class="sub-title">EXPERIENCIA</h4>
											</div>
										
											
											<div class="col s12 m12 l9">
												<div class="related-carousel">
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/paginas_web/experiencia4.jpg" alt="" />
														</div>
														<span>TURISMO Y HOTELERÍA </span>
														<h3><a href="#" title="">Presencia, entidad empresarial, adminiatrador de servicios y control de reservas </a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/paginas_web/experiencia3.jpg" alt="" />
														</div>
														<span>EDUCACIÓN</span>
														<h3><a href="#" title="">Presencia, entidad empresarial , adminiatrador de productos y administración de prematriculas</a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
															<img src="/images/paginas_web/experiencia1.jpg" alt="" />
														</div>
	                                                    <span>AUTOMÓVILES</span>
														<h3><a href="#" title="">Presencia, entidad empresarial , adminiatrador de productos y proformas</a></h3>
													</div>
													<div class="blog-post">
														<div class="blog-img">
																<img src="/images/paginas_web/experiencia2.jpg" alt="" />
														</div>
														<span>COMIDAS Y BEBIDAS</span>
														<h3><a href="#" title="">Presencia, entidad empresarial , adminiatrador de productos y cartas</a></h3>
													</div>
												
												</div><!-- Related Carousel -->
											</div>
										</div>
									</div>
								</div>
							</div>

				
							<div class="big-title" style="margin-top: 50px;margin-bottom: 50px;">
								<div class="row">
									<div class="col s12 m12 l5"><h2>METODOLOGÍA</span></h2></div>
								</div>
							</div><!-- Big Title -->
											
							<div class="single-portfolio-grids">
								<div class="row">
									<div class="col s12 m12 l12">
										<section>
											<div class="block" style="padding:0;">
												<div class="container">
													<div class="row">
														<div class="col s12 m12 l12 column">
															<div class="comments-sec">
																<div class="row">
																	<div class="col s12 m12 l9" style="width:100%;">
																		<div class="all-comments">
																			<ul>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">LA ESENCIA DEL NEGOCIO</h5>
																						<span>Objetivo de negocio</span>
																						<p>Con nuestra amplia experiencia y staff de profesionales ayudaremos a definir y a generar el valor agregado de su negocio, es el primer y gran paso que debemos dar para garantizar
																						 la redituabilidad esperada en el corto plazo.   </p>
																					</div><!-- Comment -->
																				</li>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">PLANIFICACIÓN</h5>
																						<span>Estrategia y acción</span>
																						<p>Lo acompañamos en todo momento con la estrategia que se defina como la mejor para construir su página web, somos responsable de la acción y ejecución de los objetivos planteados.</p>
																					</div><!-- Comment -->
																				</li>
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">DISEÑO</h5>
																						<span>Creatividad e innovación</span>
																						<p>Porque sabemos que no es suficiente tener una buena idea, y que es vital el como se ve y el que piensa cada cliente cuando visita su site, por ello disponemos de los mejores creativos y expertos en innovación que tienen como meta
																						desarrollar un produccto de clase mundíal</p>
																					</div><!-- Comment -->
																				</li>		
																				<li>
																					<div class="comment">
																						<h5 class="comment-name">DESARROLLO</h5>
																						<span>Gestión y análisis</span>
																						<p>Después de tener un diseño que proyecte la ideas y objetivos de negocio, se realizará el desarrollo de los diseños finalizados, en esta etapa se concreta y se edifican las bases del negocio en el gran universo del internet
                                                                                         , la calidad y tecnología empleada determinará la relevancia sobre la competencia y el liderazgo de nuestra empresa.																						</p>
																					</div><!-- Comment -->
																				</li>																						
																			</ul>

																			<div class="load-more-comments">
																				<a href="#" title=""><i class="fa fa-refresh"></i></a>
																			</div>
																		</div><!-- All Comments -->
																	</div>
																</div>
															</div>

														</div>
													</div>
												</div>
											</div>
										</section>

									</div>

								</div>
							</div><!-- Single Portfolio Grids -->

							
							
							<div class="single-portfolio-grids">
								<div class="row">
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/paginas_web/experiencia5_large.jpg" alt="" />
										
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/paginas_web/experiencia2_large.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
									<div class="col s12 m6 l4">
										<div class="portfolio-img">
											<img class="materialboxed" data-caption="A picture of some deer and tons of trees" src="/images/paginas_web/experiencia4-large.jpg" alt="" />
											<a href="#" title=""><i class="fa fa-plus"></i></a>
										</div><!-- Portfolio Image -->
									</div>
								</div>
							</div><!-- Single Portfolio Grids -->
								
						</div>
					</div>
				</div>
			</div>
	</section>

	<section id="contact">
		<div class="block no-padding">
			<div class="container">
				<div class="row">
					<div class="col s12 m12 l6 column">
						<div class="map">
							<div id="map-canvas"></div>
						</div>
					</div>
					<div class="col s12 m12 l6 offset-l6 column">
					    <?= $this->formContacto; ?>
						
					</div>
				</div>
			</div>
		</div>
	</section>
	
		
</div>

