	<!-- ================================================
	Scripts
	================================================ -->
	
	<!-- jQuery Library -->
	<script type="text/javascript" src="/js/plugins/jquery-1.11.2.min.js"></script>    
	<!--materialize js-->
	<script type="text/javascript" src="/js/materialize.js"></script>
	<script type="text/javascript" src="js/plugins/prism/prism.js"></script>
	<!--scrollbar-->
	<script type="text/javascript" src="/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

	<!-- sparkline -->
	<script type="text/javascript" src="/js/plugins/sparkline/jquery.sparkline.min.js"></script>
	<script type="text/javascript" src="/js/plugins/sparkline/sparkline-script.js"></script>
	

	<!--jvectormap-->
	<script type="text/javascript" src="/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
	<script type="text/javascript" src="/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
	<script type="text/javascript" src="/js/plugins/jvectormap/vectormap-script.js"></script>
	
	<!-- Toast Notification -->
	
	<script type="text/javascript" src="/js/plugins/data-tables//js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="/js/plugins/data-tables/data-tables-script.js"></script>

	
	<!--plugins.js - Some Specific JS codes for Plugin Settings-->
	<script type="text/javascript" src="/js/plugins.js"></script>
	<!--custom-script.js - Add your own theme custom JS-->
	<script type="text/javascript" src="/js/custom-script.js"></script>
	<script src="/js/global.js"></script>
	<script src="/js/adminservice_form.js"></script>	
	<script type="text/javascript">
	
		  // btn_crear_modal = _SQS.id("btn_guardar");
		  btn_crear_modal = document.getElementById("btn_guardarB");
		  alert(btn_crear_modal);
		 // FormService("adminserviceform","/adminservice/form/accion");
		// var FormService = new FormService({
			// id          : "adminserviceform",
			// urlRequest  : "/adminservice/form/accion"
		// });
				 // alert("bbb");
		// var PopupServiceB = new PopupServiceB({
			// urlRequest  : "/adminservice/form/crear"
		// });
			
			
		// /*Show entries on click hide*/
	
		
		
	</script>