<div class="row app-container">
    <div class="col-xs-12">

        <div class="center-block product-view-center-block">


            <div class="row product-view">
                <div class="col-xs-12">

                    <div class="row">
                        <div class="col-xs-12 col-sm-4">
                            <ul class="list-group">
                                <li class="list-group-item text-center">
                                    <div class="row">
                                        <div class="col-xs-6 col-sm-12">
                                            <img class="img-responsive" src="/_vistas/theme/eguru-2017/images/product-image-sample-6.jpg" alt="Product image">
                                        </div>
                                        <div class="col-xs-6 col-sm-12">
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <br>
                                                    <br class="hidden-sm hidden-md hidden-lg">
                                                    <br class="hidden-sm hidden-md hidden-lg">
                                                    <br class="hidden-sm hidden-md hidden-lg">

                                                    <a href="/" class="btn btn-preview">
                                                        <i class="glyphicon glyphicon-eye-open"></i>
                                                        <strong>VISTA PREVIA</strong>
                                                    </a>
                                                </div>
                                                <div class="col-xs-12">
                                                    <br>

                                                    <a href="/" class="btn btn-wish"><i class="icon-heart"></i></a>
                                                    <a href="/" class="btn btn-share"><i class="icon-share-square"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-sm-8">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="page-header">
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <h1>
                                                    <strong>Ingresos del Gobierno Central</strong>
                                                    <br>
                                                    <strong><small>Libros / Finanzas</small></strong>
                                                </h1>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row product-view-section">
                                <div class="col-xs-12">
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque nunc non dolor vulputate, bibendum aliquam quam convallis. Aenean varius ligula vitae laoreet iaculis. Vestibulum imperdiet id augue at tristique. Mauris quam enim, finibus quis commodo et, tristique vel ante. Vestibulum placerat purus nec quam cursus viverra. Integer eu elementum urna. Donec id tellus ut erat consectetur cursus. Donec id massa non augue faucibus varius vitae ac ex.
                                    </p>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque nunc non dolor vulputate, bibendum aliquam quam convallis. Aenean varius ligula vitae laoreet iaculis. Vestibulum imperdiet id augue at tristique. Mauris quam enim, finibus quis commodo et, tristique vel ante. Vestibulum placerat purus nec quam cursus viverra. Integer eu elementum urna. Donec id tellus ut erat consectetur cursus. Donec id massa non augue faucibus varius vitae ac ex.
                                    </p>
                                </div>
                                <div class="col-xs-12">
                                    <br>
                                    <a href="/" class="btn btn-sell-alternate">
                                        <i class="glyphicon glyphicon-shopping-cart"></i>
                                        <strong>$30.00</strong>
                                    </a>
                                </div>
                            </div>
                            <div class="row product-view-section property-section">
                                <div class="col-xs-12">
                                    <br>
                                    <h3>
                                        <small>Sobre el autor</small>
                                        <br>
                                        <strong>Finance and Regulation Institute - FRI ESAN</strong>
                                    </h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque nunc non dolor vulputate, bibendum aliquam quam convallis. Aenean varius ligula vitae laoreet iaculis. Vestibulum imperdiet id augue at tristique. Mauris quam enim, finibus quis commodo et, tristique vel ante. Vestibulum placerat purus nec quam cursus viverra. Integer eu elementum urna. Donec id tellus ut erat consectetur cursus. Donec id massa non augue faucibus varius vitae ac ex.
                                    </p>
                                </div>
                            </div>
                            <div class="row product-view-section property-section">
                                <div class="col-xs-12">
                                    <br>
                                    <h3>
                                        <strong>Capítulos</strong>
                                    </h3>
                                    <ul>
                                        <li>Estadísticas de la innovación internacional y nacional</li>
                                        <li>Investigación en la universidad: contexto nacional e indicadores de calidad</li>
                                        <li>Estadística sobre el uso de biotecnología en España</li>
                                        <li>Índice sintético COTEC de opinión sobre tendencias del sistema español de innovación</li>
                                        <li>El sistema de monitorización de resultados de la I+D+I desarrollado por CDTI</li>
                                        <li>I+D+i y Fashion Tech: Revelando una curiosa relación estadística con los sistemas planetarios</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="row product-view-section">
                                <div class="col-xs-12">
                                    <form class="row" method="post" action="/shopping-cart/checkout">
                                        <div class="col-xs-12 col-md-8">

                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <br>
                                                    <h3>
                                                        <strong>Consultas sobre este artículo</strong>
                                                    </h3>
                                                    <p>
                                                        Si tienes alguna consulta sobre este
                                                        producto por favor escríbenos mediante
                                                        el siguiente formulario de contacto:
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12 col-md-10">
                                                    <div class="form-group">
                                                        <textarea name="comment" class="form-control" placeholder="Escribe aquí tu consulta" rows="5"></textarea>
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-md-10 text-right">
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-confirm">
                                                            <strong>ENVIAR</strong>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>



        <br>
        <br>

        <div class="center-block home-product-list-center-block">


            <div class="row product-list">
                <div class="col-xs-12">
                    <h3 class="text-uppercase"><strong>Productos relacionados</strong></h3>

                    <div class="row">

                        <div class="col-xs-12 col-sm-6 col-md-3">




                            <div class="row card-product">
                                <div class="col-xs-12">
                                    <div class="row card-body">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <img class="img-responsive" src="/_vistas/theme/eguru-2017/images/product-image-sample-4.jpg" alt="Product image">


                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/product/curso-presencial-de-especializacion-en-recursos-humanos">
                                                        <h4><strong>Curso de Especialización en Recursos Humanos</strong></h4>
                                                    </a>
                                                    <p>
                                                        Libro | Finanzas
                                                    </p>
                                                    <p>
                                                        Brian, xD
                                                        Phasellus varius bibendum ligula nec
                                                        mollis. Aliquam tristique.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row card-footer">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/" class="btn btn-wish"><i class="icon-heart"></i></a>
                                                    <a href="/" class="btn btn-share"><i class="icon-share-square"></i></a>

                                                    <a href="/" class="btn btn-sell"><i class="glyphicon glyphicon-shopping-cart"></i> <strong>GRATIS</strong></a>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                </div>
                            </div>                </div>

                        <div class="clearfix hidden-sm hidden-md hidden-lg"></div>




                        <div class="col-xs-12 col-sm-6 col-md-3">




                            <div class="row card-product">
                                <div class="col-xs-12">
                                    <div class="row card-body">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <img class="img-responsive" src="/_vistas/theme/eguru-2017/images/product-image-sample-4.jpg" alt="Product image">


                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/product/curso-presencial-de-especializacion-en-recursos-humanos">
                                                        <h4><strong>Curso de Especialización en Recursos Humanos</strong></h4>
                                                    </a>
                                                    <p>
                                                        Libro | Finanzas
                                                    </p>
                                                    <p>
                                                        Brian, xD
                                                        Phasellus varius bibendum ligula nec
                                                        mollis. Aliquam tristique.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row card-footer">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/" class="btn btn-wish"><i class="icon-heart"></i></a>
                                                    <a href="/" class="btn btn-share"><i class="icon-share-square"></i></a>

                                                    <a href="/shopping-cart/checkout" class="btn btn-sell-now"><strong>IR A PAGAR</strong></a>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                </div>
                            </div>                </div>

                        <div class="clearfix hidden-sm hidden-md hidden-lg"></div>

                        <div class="clearfix hidden-xs hidden-md hidden-lg"></div>



                        <div class="col-xs-12 col-sm-6 col-md-3">




                            <div class="row card-product">
                                <div class="col-xs-12">
                                    <div class="row card-body">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <img class="img-responsive" src="/_vistas/theme/eguru-2017/images/product-image-sample-1.jpg" alt="Product image">


                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/product/curso-virtual-de-especializacion-en-gestion-de-procesos">
                                                        <h4><strong>Curso Especialización en Gestión de Procesos</strong></h4>
                                                    </a>
                                                    <p>
                                                        Libro | Finanzas
                                                    </p>
                                                    <p>
                                                        Brian, xD
                                                        Phasellus varius bibendum ligula nec
                                                        mollis. Aliquam tristique.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row card-footer">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/" class="btn btn-wish"><i class="icon-heart"></i></a>
                                                    <a href="/" class="btn btn-share"><i class="icon-share-square"></i></a>

                                                    <a href="/" class="btn btn-sell"><i class="glyphicon glyphicon-shopping-cart"></i> <strong>GRATIS</strong></a>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                </div>
                            </div>                </div>

                        <div class="clearfix hidden-sm hidden-md hidden-lg"></div>




                        <div class="col-xs-12 col-sm-6 col-md-3">




                            <div class="row card-product">
                                <div class="col-xs-12">
                                    <div class="row card-body">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <img class="img-responsive" src="/_vistas/theme/eguru-2017/images/product-image-sample-1.jpg" alt="Product image">


                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/product/curso-virtual-de-especializacion-en-gestion-de-procesos">
                                                        <h4><strong>Curso Especialización en Gestión de Procesos</strong></h4>
                                                    </a>
                                                    <p>
                                                        Libro | Finanzas
                                                    </p>
                                                    <p>
                                                        Brian, xD
                                                        Phasellus varius bibendum ligula nec
                                                        mollis. Aliquam tristique.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row card-footer">
                                        <div class="col-xs-12">
                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <a href="/" class="btn btn-wish"><i class="icon-heart"></i></a>
                                                    <a href="/" class="btn btn-share"><i class="icon-share-square"></i></a>

                                                    <a href="/" class="btn btn-sell"><i class="glyphicon glyphicon-shopping-cart"></i> <strong>$30.00</strong></a>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                </div>
                            </div>                </div>

                        <div class="clearfix hidden-sm hidden-md hidden-lg"></div>

                        <div class="clearfix hidden-xs hidden-md hidden-lg"></div>

                        <div class="clearfix hidden-xs hidden-sm"></div>

                    </div>

                </div>
            </div>
            <br>
            <br>
        </div>

    </div>
</div>