<!DOCTYPE html>
<html class="no-js" lang="es">
    <head>
<!-- Meta -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1"> 
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<!-- SITE TITLE -->
		<title>eGuru</title>			
		<!-- Latest Bootstrap min CSS -->
		<link rel="shortcut icon" href="/_librerias/assets/img/favicon.ico">	

		<!-- Font Awesome CSS -->
		<link rel="stylesheet" href="/_librerias/assets/fonts/font-awesome.min.css">
		<!--- owl carousel Css-->
		<link rel="stylesheet" href="/_librerias/assets/owlcarousel/css/owl.carousel.css">
		<link rel="stylesheet" href="/_librerias/assets/owlcarousel/css/owl.theme.css">		
		<!-- animate CSS -->		
		<link rel="stylesheet" href="/_librerias/assets/css/animate.css">		
		<!-- Style CSS -->
		<link rel="stylesheet" href="/_librerias/assets/css/style.css">	
		<!-- CSS FOR COLOR SWITCHER -->
		<link rel="stylesheet" href="/_librerias/assets/css/switcher/switcher.css"> 	
		<link rel="stylesheet" href="/_librerias/assets/css/switcher/style1.css" id="colors">
		
		<link rel="stylesheet" href="/_librerias/assets/css/alertify.core.css" id="colors">
		<link rel="stylesheet" href="/_librerias/assets/css/alertify.default.css" id="colors">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--font files-->
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">
        <link href="https://file.myfontastic.com/CKh2FsHovzXofp4fnzKxDP/icons.css" rel="stylesheet">
        <!--css files-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="/_librerias/assets/css/jquery.bxslider/jquery.bxslider.css">
        <link rel="stylesheet" href="/_librerias/assets/css/general.css">
        <link rel="stylesheet" href="/_librerias/assets/css/general-responsive.css">
        <!--js files-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="/_librerias/assets/css/jquery.bxslider/jquery.bxslider.js"></script>
		<script src="/_librerias/assets/js/alertify.js"></script>
		<script src="/_librerias/assets/js/alertify.min.js"></script>
		<script src="/_librerias/js/global.js"></script>
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	
		
        <?php include_once("./_librerias/php/analyticstracking.php") ?>
    </head>
    <body data-spy="scroll" data-offset="80">
		<!-- START PRELOADER -->
		<div class="preloader">
			<div class="status">
				<div class="status-mes"><h4></h4></div>
			</div>
		</div>
            <?= $this->render("_vistas/header.phtml",$propiedadesEntidad); ?>
            <?= $this->view; ?>
		    <?= $this->render("_vistas/footer.phtml",$propiedadesEntidad); ?>
		<!-- owl-carousel min js  -->
			<script src="/_librerias/assets/owlcarousel/js/owl.carousel.js"></script>	
		<!-- jquery mixitup min js -->
			<script src="/_librerias/assets/js/jquery.mixitup.js"></script>		
		<!-- scrolltopcontrol js -->
			<script src="/_librerias/assets/js/scrolltopcontrol.js"></script>
		<!-- form-contact js -->
			<script src="/_librerias/assets/js/form-contact.js"></script>			
		<!-- jquery appear js -->			
			<script src="/_librerias/assets/js/jquery.appear.js"></script>			
		<!-- WOW - Reveal Animations When You Scroll -->
			<script src="/_librerias/assets/js/wow.min.js"></script>
		<!-- map js -->

		<!-- switcher js -->
			<script src="/_librerias/assets/js/switcher.js"></script>
		<!-- scripts js -->
			<script src="/_librerias/assets/js/scripts.js"></script>
    <style>

	.MenuLateral ul {
        background-color:#000;opacity: 0.8;
	}	
	.MenuLateral ul li{
        background-color:#000;opacity: 0.8;
	}		
	.detalle_producto h4{
		color:#797979;
	}
	.detalle_producto .icono i{
		color:<?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;		
	}
	.detalle_producto .indicador .iconoID i{
		color:<?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;				
	}
	.form li button{
		background: <?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;
		border: 1px solid <?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;		
	}
	.single_social_profile ul li a i{
		color:<?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;			
	}
	.single_social_profile ul li a i:hover{
		color:#fff;	
		background: <?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;		
	}
	.topcontrol{
		background: <?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;		
	}
	.alertify-log{
		background: <?=$propiedadesEntidad["principal"]->ColorMenuHorizontal; ?>;			
	}
    </style>
    <style>
	.navbar-fixed-bottom, .navbar-fixed-top{
		position: relative;
	}	
	</style>

 
    </body>
	
	
	
</html>