	<div id="loader-wrapper">
		  <div id="loader"></div>        
		  <div class="loader-section section-left"></div>
		  <div class="loader-section section-right"></div>
	</div>

	<div id="login-page" class="row">
		<div class="col s12 z-depth-4 card-panel">
		  <form class="login-form" id="form_login_admin" method="post" >
			<div class="row">
			  <div class="input-field col s12 center">
				<img src="/images/logo.jpg" width="30" alt="" class="circle responsive-img valign profile-image-login">
				<p class="center login-form-text">FLEXZINN</p>
			  </div>
			</div>
			
			<div id="card-alert" class="card green lighten-5" style="display:none">
			  <div id="msj_form" class="card-content green-text">
				<p>DANGER : The daily report has failed</p>
			  </div>
			  <button type="button" class="close red-text" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">×</span>
			  </button>
			</div>
			
			<div class="row margin">
			  <div class="input-field col s12">
				<i class="mdi-social-person-outline prefix"></i>
				<input id="username"  name="username" type="text">
				<label for="username" class="center-align">Username</label>
			  </div>
			</div>
			<div class="row margin">
			  <div class="input-field col s12">
				<i class="mdi-action-lock-outline prefix"></i>
				<input id="password" name="password" type="password">
				<label for="password">Password</label>
			  </div>
			</div>
			<div class="row">          
			  <div class="input-field col s12 m12 l12  login-text">
				  <input type="checkbox" id="remember-me" />
				  <label for="remember-me">Remember me</label>
			  </div>
			</div>
			<div class="row">
			  <div class="input-field col s12">
				<button type="button" class="btn waves-effect waves-light col s12" id="btn_enviar" >Login</button>
			  </div>
			</div>
			<div class="row">
			  <div class="input-field col s6 m6 l6">
				<p class="margin medium-small"><a href="page-register.html">Register Now!</a></p>
			  </div>
			  <div class="input-field col s6 m6 l6">
				  <p class="margin right-align medium-small"><a href="page-forgot-password.html">Forgot password ?</a></p>
			  </div>          
			</div>

		  </form>
		</div>
	</div>


