<div class="row app-container">
    <div class="col-xs-12">

        <br>
        <br>

        <div class="center-block shopping-cart-center-block">

            <div class="row shopping-cart-product-list">
                <div class="col-xs-12">

                    <br>
                    <br>
                    <br>
                    <br>

                    <div class="row checkout-line">
                        <div class="col-xs-12">

                            <div class="row">
                                <div class="col-xs-4 checkout-step completed text-center">
                                    <div class="progress">
                                        <div class="progress-bar"></div>
                                    </div>
                                    <a class="checkout-step-circle"><strong>1</strong></a>
                                    <span>Verifica tus datos</span>
                                </div>
                                <div class="col-xs-4 checkout-step completed text-center">
                                    <div class="progress">
                                        <div class="progress-bar "></div>
                                    </div>
                                    <a  class="checkout-step-circle"><strong>2</strong></a>
                                    <span>Información de pago</span>
                                </div>
                                <div class="col-xs-4 checkout-step active text-center">
                                    <div class="progress">
                                        <div class="progress-bar"></div>
                                    </div>
                                    <a class="checkout-step-circle"><strong>3</strong></a>
                                    <span>¡Listo!</span>
                                </div>
                            </div>

                        </div>
                    </div>
                    <br>
                    <br>

                    <div class="row">
                        <div class="col-xs-12 text-center">
                            <p style="text-align: center">
                                <i class="icon-check-circle"></i>
                            </p>
                            <h1><strong>Muchas gracias por su compra</strong></h1>
                            <p class="checkout-confirmed-message" style="text-align: center;">
                                Tu compra ha sido procesada correctamente.
                                Puedes ver el <br class="hidden-xs"> estado de compra desde la
                                sección "Compras"
                            </p>
                            <br>
                            <a href="/compras-realizadas/entidad/<?= $viewDataArray["empresa"]; ?>" class="btn btn-confirm"><strong>VER COMPRAS</strong></a>
                        </div>
                    </div>

                </div>
            </div>

            <br>
            <br>
            <br>

        </div>
    </div>
</div>