		<section id="about" class="feature section-padding" style="padding:10px 5%;">
			<div class="container-fluid">
				<div class="row text-center">
				
					<div class="col-md-3 col-sm-6 col-xs-12" style="width:25%" data-wow-duration="1s" data-wow-delay="0.1s" data-wow-offset="0">
					    <div class="panel_img_productos" style="background: #fff;">
							<div class="img" style="background: #fff;margin: 10px;">
							    <img src="/_imagenes/productos/imagen1.jpg" width="250px">
							</div>	
                        </div>						
					</div><!--- END COL -->			
					
					<div class="col-md-8 col-sm-6 col-xs-12" style="width:74%;padding: 20px 25px;" data-wow-duration="1s" data-wow-delay="0.2s" data-wow-offset="0">	
					    <div class="detalle_producto">
						
						<!--- TITULO -->	
						    <div class="seccion">
								<div class="col-md-3 col-sm-6 col-xs-12" style="width:100%;padding: 0px;" data-wow-duration="1s" data-wow-delay="0.1s" data-wow-offset="0">
									<div class="titulo" >
										<h1 style="margin: 10px 0px 10px 0px;">Laptop HP78929292</h1>
										<p>Tecnología | Laptops</p>
										
									</div>
									<div class="botonera" >
										<div class="single_social_profileA" style="padding: 9px 0px 0px 0px;">
										
											<ul class="nav navbar-nav navbar-left" style="margin:0px 0px 0px 0px;">
												<li><a href="https://www.youtube.com/channel/UClZU0FsXjVJsLesH8HFbsVg" class="btn_text_storeS"> <i class="fa fa-heart" style="color:red;"></i></a></li>
												<li><a href="/productoeducativo/id/12" class="btn_text_storeS"> <i class="fa fa-share" style="color:black;"></i></a></li>
											</ul>
										
										</div>								
									</div>	
								</div>
							</div>
						<!--- END TITULO -->	
							
							<!--- TEMAS -->	
							<div class="seccion">
								<div class="col-md-3 col-sm-6 col-xs-12" style="width:100%;padding: 0px;" data-wow-duration="1s" data-wow-delay="0.1s" data-wow-offset="0">
							
									<p style="color: #58585b;">
									2 instagram post, 2 facebook cover, 2 facebook news feed and 2 facebook post,
									Editable Layer Psd files Vector Shapes 
									Smart Object for edit image (instruction given in help file)
									</p>													
								</div>	
							</div>
							<!--- END TEMAS -->	
							
						<!--- BOTONERA -->								
						    <div class="seccion">
								<div class="col-md-3 col-sm-6 col-xs-12" style="width:100%;padding: 0px;" data-wow-duration="1s" data-wow-delay="0.1s" data-wow-offset="0">
									<div class="botonera" >
										<div class="single_social_profileA" style="padding: 9px 0px 0px 0px;">
											<ul class="nav navbar-nav navbar-left" style="margin:0px 0px 0px 0px;">
												<li><a href="https://www.youtube.com/channel/UClZU0FsXjVJsLesH8HFbsVg" class='btn_accion'> <i class="fa fa-cart-plus"></i>$ 10.00</a></li>
											</ul>
										
										</div>								
									</div>	
								</div>
							</div>
						    <!--- END BOTONERA -->								
							
							<!--- REQUISITOS -->	
							<div class="seccion">
								<div class="col-md-3 col-sm-6 col-xs-12" style="width:100%;padding: 0px;" data-wow-duration="1s" data-wow-delay="0.1s" data-wow-offset="0">
									<h4>Características</h4>
									<p style="color: #58585b;">
									2 instagram post, 2 facebook cover, 2 facebook news feed and 2 facebook post,
									Editable Layer Psd files Vector Shapes 
									Smart Object for edit image (instruction given in help file)
									</p>													
								</div>	
							</div>
							<!--- END REQUISITOS -->								
							
							<!--- REQUISITOS -->	
							<div class="seccion">
							
								<div class="col-md-3 col-sm-6 col-xs-12" style="width:100%;padding: 0px;" data-wow-duration="1s" data-wow-delay="0.1s" data-wow-offset="0">
									<h4>Fabricante</h4>
									<p style="color: #58585b;">
									2 instagram post, 2 facebook cover, 2 facebook news feed and 2 facebook post,
									Editable Layer Psd files Vector Shapes 
									Smart Object for edit image (instruction given in help file)
									</p>													
								</div>	
							</div>
							<!--- END REQUISITOS -->								

							<!--- FORM INSCRIPCION -->	
							<div class="seccion">
								
								<div class="col-md-3 col-sm-6 col-xs-12" style="width:100%;padding:0px;" data-wow-duration="1s" data-wow-delay="0.1s" data-wow-offset="0">
									<h4>Consultas</h4>
									<p>
									2 instagram post, 2 facebook cover, 2 facebook news feed and 2 facebook post,
									Editable Layer Psd files Vector Shapes 
									</p>
									<div class="form">
										<form>
										<li><label>Nombres</label><input type="text" name="nombres"></li>
										<li><label>Email</label><input type="text" name="Email"></li>
										<li><label>Mensaje</label><textarea rows="4" cols="50"></textarea></li>
										<li style="text-align:right;"><button type="submit" value="ENVIAR">ENVIAR</button></li>
										</form>
									</div>								
								</div>		
								
							</div>
							<!--- END INSCRIPCION -->							
													
			            </div><!--- END CONTAINER -->
			        </div><!--- END CONTAINER -->
			    </div><!--- END CONTAINER -->
			</div><!--- END CONTAINER -->
		</section>

		
		
		