<div class="row app-container">
    <div class="col-xs-12">

        <div class="center-block product-view-center-block">

            <div class="row product-view">
                <div class="col-xs-12">

                    <div class="row">
                        <div class="col-xs-12">
                            <br>
                            <br>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-6">
                            <div class="row">
                                <div class="col-xs-12">
                                    <h1>
                                        <strong>Únete a eGurú</strong>
                                    </h1>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut nisi venenatis, ullamcorper felis eu, condimentum ligula.
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <br>
                                    <br>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-6 col-sm-4 text-center">
                                    <div class="register-information-item">
                                        <i class="icon-file-o"></i>
                                        <h4>
                                            <strong>Libros gratis</strong>
                                        </h4>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-4 text-center">
                                    <div class="register-information-item">
                                        <i class="icon-coffee"></i>
                                        <h4>
                                            <strong>Compra donde quieras</strong>
                                        </h4>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-4 text-center">
                                    <div class="register-information-item">
                                        <i class="icon-burst-sale"></i>
                                        <h4>
                                            <strong>Ofertas especiales</strong>
                                        </h4>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-8 text-center hidden-xs">
                                    <div class="register-information-item">
                                        <br>
                                        <img src="/_vistas/theme/eguru-2017/images/credit-cards.png" class="img-responsive" alt="Credit cards image">
                                        <br>
                                        <br>
                                        <h4>
                                            <strong>Paga en línea con tranquilidad</strong>
                                        </h4>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-4 text-center">
                                    <div class="register-information-item">
                                        <i class="glyphicon glyphicon-eye-open"></i>
                                        <h4>
                                            <strong>Lee tus libros en cualquier lugar</strong>
                                        </h4>
                                    </div>
                                </div>
                                <div class="col-xs-12 text-center hidden-sm hidden-md hidden-lg">
                                    <div class="register-information-item">
                                        <br>
                                        <img src="/_vistas/theme/eguru-2017/images/credit-cards.png" class="img-responsive" alt="Credit cards image">
                                        <br>
                                        <br>
                                        <h4>
                                            <strong>Paga en línea con tranquilidad</strong>
                                        </h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4 col-md-offset-1 col-lg-offset-2">

                            <form class="row" method="post" action='javascript:void(null);'  enctype='multipart/form-data' id="formularioDatosRegistro">
                                <div class="col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 col-md-12">
                                            <br>
                                            <button type="button" class="btn btn-block btn-facebook">
                                                <i class="icon-facebook"></i>
                                                <strong>Registrate con Facebook</strong>
                                            </button>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 col-md-12">
                                            <br>
                                            <button type="button" class="btn btn-block btn-google">
                                                <i class="icon-google-plus"></i>
                                                <strong>Registrate con Google+</strong>
                                            </button>
                                        </div>
                                        <div class="col-xs-12 text-center">
                                            <br>
                                            Al ingresar acepto los <a href="/" target="_blank">términos y condiciones</a>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-12 col-md-offset-0">

                                            <div class="row">
                                                <div class="col-xs-12 text-center">
                                                    <hr>
                                                    <h4><strong>o regístrate manualmente</strong></h4>
                                                    <br>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <input type="text" name="name" class="form-control" placeholder="Nombres">
                                                    </div>
                                                </div>
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <input type="text" name="lastname" class="form-control" placeholder="Apellidos">
                                                    </div>
                                                </div>
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <input type="text" name="email" class="form-control" placeholder="Correo electrónico">
                                                    </div>
                                                </div>
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <input type="password" name="password" class="form-control" placeholder="Contraseña">
                                                    </div>
                                                </div>
                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <input type="checkbox" checked="true" name="terminos" id="terms-conditions">
                                                        <label for="terms-conditions">Acepto los <a href="/" target="_blank">términos y condiciones</a></label>
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 text-right">
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-confirm text-uppercase" id="botonRegistro">
                                                            <strong>Registrar</strong>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <br>
                            <br>
                            <br>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>
</div>


<script>	
$('#botonRegistro').on('click', '', function (e) {
	registrar();
});				
function registrar() {
        ///lanzamiento del API de culqui
		
		///Si el retorno del proceso de pago mediante culqui es TRUE, cierra la proforma 
	    var ruta = '/system/_vistas/se_usuario_tienda.php?Main=registro&entidad=<?php echo $empresa; ?>';

		$.ajax({                        
           type: "POST",                 
           url: ruta,                     
           data: $("#formularioDatosRegistro").serialize(), 
           success: function(data)             
           {
			   
			   	// alertify.success(data);
			    if(data=="true"){
					alertify.success("Su usuario fue creado con éxito");
					var explode = function(){
						location.href="/<?php echo $empresa; ?>";
					};
					setTimeout(explode, 3000);					
				}else{
					alertify.success("Su email ya existe");					
				}


           }
        });
		///Si el retorno del proceso de pago mediante culqui es FALSE, deja a la proforma en un estado de intento fallido 		
}	
</script>

