<div class="row app-container">
    <div class="col-xs-12">

        <div class="center-block product-view-center-block">

            <div class="row product-view">
                <div class="col-xs-12">

                    <div class="row">
                        <div class="col-xs-12">
                            <div class="page-header">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <h1>
                                            <strong>Términos y condiciones</strong>
                                        </h1>
                                        <span>Última Versión</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <br>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p><?= $datosEmpresa->TerminosCondiciones; ?>
							</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <br>
                            <br>
                            <br>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>
</div>