<!doctype html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Color Thief</title>
  <link rel="stylesheet" href="color-thief-master/examples/css/screen.css">

</head>
<body>


  <section id="drag-drop" class="drag-drop-section">
    <div class="container">
      <h2>Try it yourself</h2>
      <div id="drop-zone" class="drop-zone">
        <div class="drop-zone-label default-label">Drag an image here</div>
        <div class="drop-zone-label dragging-label">Drop it!</div>
      </div>
      <div id="dragged-images" class="dragged-images"></div>
    </div>
  </section>



  <!-- Mustache templates -->
  <script id='image-section-template' type='text/x-mustache'>
    {{#images}}
    <div class="image-section {{class}}">
      <div class="image-wrap">
        <button class="run-functions-button">
          <span class="no-touch-label">Click</span>
          <span class="touch-label">Tap</span>
        </button>
        <img class="target-image" src="{{file}}" />
      </div>
      <div class="color-thief-output"></div>
    </div>
    {{/images}}
  </script>

  <script id="color-thief-output-template" type="text/x-mustache">
    <div class="function get-color">
      <h3 class="function-title">Dominant Color</h3>
      <div class="swatches">
        <div class="swatch" style="background-color: rgb({{color.0}}, {{color.1}}, {{color.2}})"></div>
      </div>
      <div class="function-code">
        <code>colorThief.getColor(image):{{elapsedTimeForGetColor}}ms</code>
      </div>
    </div>
    <div class="function get-palette">
      <h3 class="function-title">Palette</h3>
      <div class="function-output">
        <div class="swatches">
          {{#palette}}
            <div class="swatch" style="background-color: rgb({{0}}, {{1}}, {{2}})"></div>
          {{/palette}}
        </div>
      </div>
      <div class="function-code">
        <code>colorThief.getPalette(image):{{elapsedTimeForGetPalette}}ms</code>
      </div>
    </div>
  </script>

  <script src="color-thief-master/src/color-thief.js"></script>
  <script src="color-thief-master/examples/js/jquery.js"></script>
  <script src="color-thief-master/examples/js/mustache.js"></script>
  <script src="color-thief-master/examples/js/demo.js"></script>

</body>
</html>
